// Mock data - in production, this would come from a database
export const mockApplications = [
  {
    id: "1",
    jobId: "1",
    jobTitle: "Senior Frontend Developer",
    applicantName: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 123-4567",
    linkedIn: "https://linkedin.com/in/johnsmith",
    experience: "6 years",
    availability: "2 weeks notice",
    coverLetter:
      "I am excited to apply for the Senior Frontend Developer position...",
    resumeFileName: "john_smith_resume.pdf",
    status: "pending",
    appliedAt: "2024-01-15T10:30:00Z",
    lastUpdated: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    jobId: "1",
    jobTitle: "Senior Frontend Developer",
    applicantName: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 987-6543",
    experience: "8 years",
    availability: "Immediately",
    coverLetter: "With over 8 years of React experience...",
    resumeFileName: "sarah_johnson_resume.pdf",
    status: "reviewing",
    appliedAt: "2024-01-14T14:20:00Z",
    lastUpdated: "2024-01-16T09:15:00Z",
  },
  {
    id: "3",
    jobId: "2",
    jobTitle: "Backend Engineer",
    applicantName: "Mike Chen",
    email: "mike.chen@email.com",
    phone: "+1 (555) 456-7890",
    experience: "5 years",
    availability: "1 month notice",
    resumeFileName: "mike_chen_resume.pdf",
    status: "accepted",
    appliedAt: "2024-01-13T16:45:00Z",
    lastUpdated: "2024-01-17T11:30:00Z",
  },
  {
    id: "4",
    jobId: "3",
    jobTitle: "Product Designer",
    applicantName: "Emily Davis",
    email: "emily.davis@email.com",
    phone: "+1 (555) 321-0987",
    linkedIn: "https://linkedin.com/in/emilydavis",
    experience: "4 years",
    availability: "3 weeks notice",
    coverLetter: "I am passionate about creating user-centered designs...",
    resumeFileName: "emily_davis_portfolio.pdf",
    status: "rejected",
    appliedAt: "2024-01-12T11:15:00Z",
    lastUpdated: "2024-01-18T14:20:00Z",
  },
];

export const mockJobs = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    department: "Engineering",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120,000 - $160,000",
    description:
      "We're looking for a senior frontend developer to join our engineering team and help build the next generation of our web applications.",
    requirements: [
      "5+ years of React experience",
      "TypeScript proficiency",
      "Modern CSS frameworks",
    ],
    responsibilities: [
      "Develop React applications",
      "Code reviews",
      "Mentor junior developers",
    ],
    benefits: ["Health insurance", "Stock options", "Remote work"],
    status: "active",
    posted: "2024-01-10T00:00:00Z",
    applicationsCount: 12,
  },
  {
    id: "2",
    title: "Backend Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    salary: "$110,000 - $150,000",
    description:
      "Join our backend team to design and implement scalable APIs and microservices that power our platform.",
    requirements: [
      "Node.js/Python experience",
      "Database design",
      "Cloud platforms (AWS/GCP)",
    ],
    status: "active",
    posted: "2024-01-08T00:00:00Z",
    applicationsCount: 8,
  },
  {
    id: "3",
    title: "Product Designer",
    department: "Design",
    location: "New York, NY",
    type: "Full-time",
    salary: "$90,000 - $130,000",
    description:
      "We're seeking a talented product designer to create intuitive and beautiful user experiences for our products.",
    requirements: [
      "Figma expertise",
      "User research experience",
      "Design systems knowledge",
    ],
    status: "active",
    posted: "2024-01-12T00:00:00Z",
    applicationsCount: 15,
  },
];
